pres=int(input('Введите давление(в Паскалях)'))
vol=int(input('Введите объём(в м^3)'))
temp=int(input('Введите температуру(в Кельвинах)'))
amount=(pres*vol)/(8.31*temp)
print('Количество вещества:',amount)